/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package group9_trafficlightcontrolsystem;
import javax.swing.Timer;
import java.awt.event.*;
import javax.swing.ImageIcon;
import java.awt.Color;
import java.awt.Image;
import java.util.Queue;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author user
 */
public class TrafficModel extends javax.swing.JFrame {
    String currentActiveDirection = "N";
    javax.swing.JLabel currentGreen;
    javax.swing.JLabel readyToYellow;
    javax.swing.JLabel readyToRed;
    
    public TrafficModel() {
        this.readyToYellow = yellowlight_North;
        this.readyToRed = redlight_North;
        this.currentGreen = greenlight_North; 
        
        initComponents();
        this.setLocationRelativeTo(null);//center form in the screen
        
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        greenlight_Pedestrain = new javax.swing.JLabel();
        redlight_Pedestrain = new javax.swing.JLabel();
        yellowlight_Pedestrain = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pedestrian = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        trafficLightBackground_North = new javax.swing.JPanel();
        redlight_North = new javax.swing.JLabel();
        yellowlight_North = new javax.swing.JLabel();
        greenlight_North = new javax.swing.JLabel();
        northCar1 = new javax.swing.JLabel();
        north = new javax.swing.JLabel();
        northCar2 = new javax.swing.JLabel();
        northCar3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        northCar5 = new javax.swing.JLabel();
        northCar6 = new javax.swing.JLabel();
        northCar4 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        instruction = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        trafficLightBackground = new javax.swing.JPanel();
        redlight_West = new javax.swing.JLabel();
        yellowlight_West = new javax.swing.JLabel();
        greenlight_West = new javax.swing.JLabel();
        westCar1 = new javax.swing.JLabel();
        westCar2 = new javax.swing.JLabel();
        west = new javax.swing.JLabel();
        westCar3 = new javax.swing.JLabel();
        westCar4 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        westCar5 = new javax.swing.JLabel();
        westCar6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        trafficLightBackground_North1 = new javax.swing.JPanel();
        redlight_East = new javax.swing.JLabel();
        yellowlight_East = new javax.swing.JLabel();
        greenlight_East = new javax.swing.JLabel();
        east = new javax.swing.JLabel();
        eastCar2 = new javax.swing.JLabel();
        eastCar1 = new javax.swing.JLabel();
        eastCar3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tovertical1 = new javax.swing.JLabel();
        eastCar5 = new javax.swing.JLabel();
        eastCar6 = new javax.swing.JLabel();
        eastCar4 = new javax.swing.JLabel();
        fromEast = new javax.swing.JLabel();
        toSouthOrWest = new javax.swing.JLabel();
        toWest = new javax.swing.JLabel();
        fromWest = new javax.swing.JLabel();
        toEast = new javax.swing.JLabel();
        toNorthOrEast = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        trafficLightBackground1 = new javax.swing.JPanel();
        redlight_South = new javax.swing.JLabel();
        yellowlight_South = new javax.swing.JLabel();
        greenlight_South = new javax.swing.JLabel();
        south = new javax.swing.JLabel();
        southCar1 = new javax.swing.JLabel();
        southCar3 = new javax.swing.JLabel();
        southCar2 = new javax.swing.JLabel();
        southCar4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Traffic Light Control System Simulation");
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(204, 204, 204));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel5.setDoubleBuffered(false);
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel7.setBackground(new java.awt.Color(102, 102, 102));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jPanel12.setBackground(new java.awt.Color(0, 0, 0));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        greenlight_Pedestrain.setBackground(new java.awt.Color(255, 255, 255));
        greenlight_Pedestrain.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        greenlight_Pedestrain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        greenlight_Pedestrain.setText("P");
        greenlight_Pedestrain.setOpaque(true);
        jPanel12.add(greenlight_Pedestrain, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 50, 40));

        redlight_Pedestrain.setBackground(new java.awt.Color(255, 255, 255));
        redlight_Pedestrain.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        redlight_Pedestrain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        redlight_Pedestrain.setText("P");
        redlight_Pedestrain.setOpaque(true);
        jPanel12.add(redlight_Pedestrain, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 50, 40));

        yellowlight_Pedestrain.setBackground(new java.awt.Color(255, 255, 255));
        yellowlight_Pedestrain.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        yellowlight_Pedestrain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        yellowlight_Pedestrain.setText("P");
        yellowlight_Pedestrain.setOpaque(true);
        jPanel12.add(yellowlight_Pedestrain, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 50, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel6.setText("Pedestrian Crossing Light");

        pedestrian.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        pedestrian.setText("Pedestrian");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pedestrian)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(pedestrian)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jPanel7.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 280));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 292, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 262, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 300, 270));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        trafficLightBackground_North.setBackground(new java.awt.Color(0, 0, 0));

        redlight_North.setBackground(new java.awt.Color(255, 255, 255));
        redlight_North.setOpaque(true);

        yellowlight_North.setBackground(new java.awt.Color(255, 255, 255));
        yellowlight_North.setOpaque(true);

        greenlight_North.setBackground(new java.awt.Color(255, 255, 255));
        greenlight_North.setOpaque(true);

        javax.swing.GroupLayout trafficLightBackground_NorthLayout = new javax.swing.GroupLayout(trafficLightBackground_North);
        trafficLightBackground_North.setLayout(trafficLightBackground_NorthLayout);
        trafficLightBackground_NorthLayout.setHorizontalGroup(
            trafficLightBackground_NorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trafficLightBackground_NorthLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(redlight_North, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(yellowlight_North, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(greenlight_North, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        trafficLightBackground_NorthLayout.setVerticalGroup(
            trafficLightBackground_NorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trafficLightBackground_NorthLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(trafficLightBackground_NorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(redlight_North, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yellowlight_North, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(greenlight_North, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(trafficLightBackground_North, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 224, 140, -1));

        northCar1.setBackground(new java.awt.Color(0, 0, 0));
        northCar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        northCar1.setOpaque(true);
        northCar1.setVisible(false);
        jPanel1.add(northCar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 40, 60));

        north.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        north.setText("NORTH");
        jPanel1.add(north, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        northCar2.setBackground(new java.awt.Color(0, 0, 0));
        northCar2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        northCar2.setOpaque(true);
        northCar2.setVisible(false);
        jPanel1.add(northCar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 40, 60));

        northCar3.setBackground(new java.awt.Color(0, 0, 0));
        northCar3.setForeground(new java.awt.Color(255, 255, 255));
        northCar3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        northCar3.setOpaque(true);
        northCar3.setVisible(false);
        jPanel1.add(northCar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 40, 60));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("N");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, -1, -1));

        northCar5.setBackground(new java.awt.Color(0, 0, 0));
        northCar5.setForeground(new java.awt.Color(255, 255, 255));
        northCar5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        northCar5.setOpaque(true);
        northCar5.setVisible(false);
        jPanel1.add(northCar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 40, 60));

        northCar6.setBackground(new java.awt.Color(0, 0, 0));
        northCar6.setForeground(new java.awt.Color(255, 255, 255));
        northCar6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        northCar6.setOpaque(true);
        northCar6.setVisible(false);
        jPanel1.add(northCar6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 40, 60));

        northCar4.setBackground(new java.awt.Color(0, 0, 0));
        northCar4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        northCar4.setOpaque(true);
        northCar4.setVisible(false);
        jPanel1.add(northCar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 40, 60));

        jPanel7.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 350, -1));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        instruction.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        instruction.setText("Instruction");
        instruction.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(instruction)
                .addContainerGap(183, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(instruction)
                .addContainerGap(200, Short.MAX_VALUE))
        );

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 310, 280));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 302, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 252, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 580, 310, 260));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        trafficLightBackground.setBackground(new java.awt.Color(0, 0, 0));

        redlight_West.setBackground(new java.awt.Color(255, 255, 255));
        redlight_West.setOpaque(true);

        yellowlight_West.setBackground(new java.awt.Color(255, 255, 255));
        yellowlight_West.setOpaque(true);

        greenlight_West.setBackground(new java.awt.Color(255, 255, 255));
        greenlight_West.setOpaque(true);

        javax.swing.GroupLayout trafficLightBackgroundLayout = new javax.swing.GroupLayout(trafficLightBackground);
        trafficLightBackground.setLayout(trafficLightBackgroundLayout);
        trafficLightBackgroundLayout.setHorizontalGroup(
            trafficLightBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trafficLightBackgroundLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(trafficLightBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(redlight_West, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yellowlight_West, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(greenlight_West, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        trafficLightBackgroundLayout.setVerticalGroup(
            trafficLightBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trafficLightBackgroundLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(redlight_West, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(yellowlight_West, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(greenlight_West, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(trafficLightBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 2, -1, 133));

        westCar1.setBackground(new java.awt.Color(0, 0, 0));
        westCar1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        westCar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        westCar1.setOpaque(true);
        westCar1.setVisible(false);
        jPanel2.add(westCar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 60, 40));

        westCar2.setBackground(new java.awt.Color(0, 0, 0));
        westCar2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        westCar2.setOpaque(true);
        westCar2.setVisible(false);
        jPanel2.add(westCar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 60, 40));

        west.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        west.setText("WEST");
        jPanel2.add(west, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        westCar3.setBackground(new java.awt.Color(0, 0, 0));
        westCar3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        westCar3.setOpaque(true);
        westCar3.setVisible(false);
        jPanel2.add(westCar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 60, 40));

        westCar4.setBackground(new java.awt.Color(0, 0, 0));
        westCar4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        westCar4.setOpaque(true);
        westCar4.setVisible(false);
        jPanel2.add(westCar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 60, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("W");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel5.setText("___________________________");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 260, 50));

        westCar5.setBackground(new java.awt.Color(0, 0, 0));
        westCar5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        westCar5.setOpaque(true);
        westCar5.setVisible(false);
        jPanel2.add(westCar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 60, 40));

        westCar6.setBackground(new java.awt.Color(0, 0, 0));
        westCar6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        westCar6.setOpaque(true);
        westCar6.setVisible(false);
        jPanel2.add(westCar6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 60, 40));

        jPanel6.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 280));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        trafficLightBackground_North1.setBackground(new java.awt.Color(0, 0, 0));

        redlight_East.setBackground(new java.awt.Color(255, 255, 255));
        redlight_East.setOpaque(true);

        yellowlight_East.setBackground(new java.awt.Color(255, 255, 255));
        yellowlight_East.setOpaque(true);

        greenlight_East.setBackground(new java.awt.Color(255, 255, 255));
        greenlight_East.setOpaque(true);

        javax.swing.GroupLayout trafficLightBackground_North1Layout = new javax.swing.GroupLayout(trafficLightBackground_North1);
        trafficLightBackground_North1.setLayout(trafficLightBackground_North1Layout);
        trafficLightBackground_North1Layout.setHorizontalGroup(
            trafficLightBackground_North1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trafficLightBackground_North1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(trafficLightBackground_North1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(redlight_East, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yellowlight_East, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(greenlight_East, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        trafficLightBackground_North1Layout.setVerticalGroup(
            trafficLightBackground_North1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trafficLightBackground_North1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(redlight_East, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(yellowlight_East, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(greenlight_East, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(trafficLightBackground_North1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 56, -1));

        east.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        east.setText("EAST");
        jPanel3.add(east, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        eastCar2.setBackground(new java.awt.Color(0, 0, 0));
        eastCar2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        eastCar2.setOpaque(true);
        eastCar2.setVisible(false);
        jPanel3.add(eastCar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 60, 40));

        eastCar1.setBackground(new java.awt.Color(0, 0, 0));
        eastCar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        eastCar1.setOpaque(true);
        eastCar1.setVisible(false);
        jPanel3.add(eastCar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 60, 40));

        eastCar3.setBackground(new java.awt.Color(0, 0, 0));
        eastCar3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        eastCar3.setOpaque(true);
        eastCar3.setVisible(false);
        jPanel3.add(eastCar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 60, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("E");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, -1, -1));

        tovertical1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        tovertical1.setText("______________________________");
        jPanel3.add(tovertical1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        eastCar5.setBackground(new java.awt.Color(0, 0, 0));
        eastCar5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        eastCar5.setOpaque(true);
        eastCar5.setVisible(false);
        jPanel3.add(eastCar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 60, 40));

        eastCar6.setBackground(new java.awt.Color(0, 0, 0));
        eastCar6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        eastCar6.setOpaque(true);
        eastCar6.setVisible(false);
        jPanel3.add(eastCar6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 60, 40));

        eastCar4.setBackground(new java.awt.Color(0, 0, 0));
        eastCar4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        eastCar4.setOpaque(true);
        eastCar4.setVisible(false);
        jPanel3.add(eastCar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 60, 40));

        jPanel6.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 310, -1));

        fromEast.setBackground(new java.awt.Color(0, 0, 0));
        fromEast.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fromEast.setOpaque(true);
        fromEast.setVisible(false);
        jPanel6.add(fromEast, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, 70, 40));

        toSouthOrWest.setBackground(new java.awt.Color(0, 0, 0));
        toSouthOrWest.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        toSouthOrWest.setOpaque(true);
        toSouthOrWest.setVisible(false);
        jPanel6.add(toSouthOrWest, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 40, 60));

        toWest.setBackground(new java.awt.Color(0, 0, 0));
        toWest.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        toWest.setOpaque(true);
        toWest.setVisible(false);
        jPanel6.add(toWest, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 70, 40));

        fromWest.setBackground(new java.awt.Color(0, 0, 0));
        fromWest.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fromWest.setOpaque(true);
        fromWest.setVisible(false);
        jPanel6.add(fromWest, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 70, 40));

        toEast.setBackground(new java.awt.Color(0, 0, 0));
        toEast.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        toEast.setOpaque(true);
        toEast.setVisible(false);
        jPanel6.add(toEast, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 70, 40));

        toNorthOrEast.setBackground(new java.awt.Color(0, 0, 0));
        toNorthOrEast.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        toNorthOrEast.setOpaque(true);
        toNorthOrEast.setVisible(false);
        jPanel6.add(toNorthOrEast, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 40, 60));

        jPanel7.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, -1, 300));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        trafficLightBackground1.setBackground(new java.awt.Color(0, 0, 0));
        trafficLightBackground1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        redlight_South.setBackground(new java.awt.Color(255, 255, 255));
        redlight_South.setOpaque(true);
        trafficLightBackground1.add(redlight_South, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 35, 35));

        yellowlight_South.setBackground(new java.awt.Color(255, 255, 255));
        yellowlight_South.setOpaque(true);
        trafficLightBackground1.add(yellowlight_South, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 35, 35));

        greenlight_South.setBackground(new java.awt.Color(255, 255, 255));
        greenlight_South.setOpaque(true);
        trafficLightBackground1.add(greenlight_South, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 35, 35));

        jPanel4.add(trafficLightBackground1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 137, 58));

        south.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        south.setText("SOUTH");
        jPanel4.add(south, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, -1, -1));

        southCar1.setBackground(new java.awt.Color(0, 0, 0));
        southCar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        southCar1.setOpaque(true);
        southCar1.setVisible(false);
        jPanel4.add(southCar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 40, 57));

        southCar3.setBackground(new java.awt.Color(0, 0, 0));
        southCar3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        southCar3.setOpaque(true);
        southCar3.setVisible(false);
        jPanel4.add(southCar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 40, 57));

        southCar2.setBackground(new java.awt.Color(0, 0, 0));
        southCar2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        southCar2.setOpaque(true);
        southCar2.setVisible(false);
        jPanel4.add(southCar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 40, 57));

        southCar4.setBackground(new java.awt.Color(0, 0, 0));
        southCar4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        southCar4.setOpaque(true);
        southCar4.setVisible(false);
        jPanel4.add(southCar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 40, 57));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("S");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 10, 20));

        jPanel7.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 580, 340, 250));

        jPanel5.add(jPanel7, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 817, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        getAccessibleContext().setAccessibleName("Traffic Light");

        pack();
    }// </editor-fold>//GEN-END:initComponents
//int a=0;
//int b =0;
//Timer carTimer = new Timer(10,new ActionListener(){
//   public void actionPerformed(ActionEvent e)
//   {
//       b++;
//       car.setLocation(b,250);
//       if(b==300){
//           b=0;
//       }
//   }
//});
//
//Timer timer2 = new Timer(1000,new ActionListener(){
//   public void actionPerformed(ActionEvent e)
//   {
//       a++;
//       switch(a){
//           case 2:
//           {
//               greenlight_goEast.setBackground(Color.white);
//               redlight_goEast.setBackground(Color.red);
//               carTimer.stop();
//               break;
//           }
//           case 4:
//           {
//               redlight_goEast.setBackground(Color.white);
//               yellowlight_goEast.setBackground(Color.yellow);
//               break;
//           }
//           case 6:
//           {
//               yellowlight_goEast.setBackground(Color.white);
//               greenlight_goEast.setBackground(Color.green);
//               carTimer.start();
//               break;
//           }
//       }
//       if(a==6){
//           a=0;
//       }
//   }
//});
/***************************************************************
* To set traffic light to GREEN/YELLOW
* ***************************************************************/  
    public void setWhichDirectionToColor(String occupied, String color){
        Color colorToSet = color.equals("G") ? Color.green : 
                            color.equals("Y") ? Color.yellow : Color.red;
        
        if(color.equals("G")){
            if(currentGreen != null)
                currentGreen.setBackground(Color.white);
            
            if(occupied.equals("N")){
                currentGreen = greenlight_North;
                readyToYellow = yellowlight_North;
                readyToRed = redlight_North;
            }
            else if(occupied.equals("S")){
                currentGreen = greenlight_South;
                readyToYellow = yellowlight_South;
                readyToRed = redlight_South;
            }
            else if(occupied.equals("W")){
                currentGreen = greenlight_West;
                readyToYellow = yellowlight_West;
                readyToRed = redlight_West;
            }
            else if(occupied.equals("E")){
                currentGreen = greenlight_East;
                readyToYellow = yellowlight_East;
                readyToRed = redlight_East;
            }else{
                currentGreen = greenlight_Pedestrain;
                readyToYellow = yellowlight_Pedestrain;
                readyToRed = redlight_Pedestrain;
            }
            currentGreen.setBackground(colorToSet);
            readyToRed.setBackground(Color.white);
            setOtherDirectionToRed(occupied);
        }
        else if(color.equals("Y")){
            currentGreen.setBackground(Color.white);
            readyToYellow.setBackground(colorToSet);
        }
        else{
            readyToYellow.setBackground(Color.white);
            readyToRed.setBackground(colorToSet);
        }
    }

/***************************************************************
* To set traffic light to RED
* ***************************************************************/    
    public void setOtherDirectionToRed(String occupied){
        if(!occupied.equals("N"))
            redlight_North.setBackground(Color.red);
        
        if(!occupied.equals("S"))
            redlight_South.setBackground(Color.red);
        
        if(!occupied.equals("W"))
            redlight_West.setBackground(Color.red);
        
        if(!occupied.equals("E"))
            redlight_East.setBackground(Color.red);
        
        if(!occupied.equals("P"))
            redlight_Pedestrain.setBackground(Color.red);
    }
    
/***************************************************************
* To display the which traffic light is GREEN/YELLOW/RED
* ***************************************************************/
    public void setInstruction(String instruction){
        this.instruction.setText(instruction);
    }
/***************************************************************
* To display total car/pedestrian waiting in each traffic light
* ***************************************************************/    
    public void setNorthTotalCar(int total){
        north.setText("Total Car:"+String.valueOf(total));
    }
    public void setSouthTotalCar(int total){
        south.setText("Total Car:"+String.valueOf(total));
    }
    public void setWestTotalCar(int total){
        west.setText("Total Car:"+String.valueOf(total));
    }
    public void setEastTotalCar(int total){
        east.setText("Total Car:"+String.valueOf(total));
    }
    public void setPedestrian(String instruction){
        pedestrian.setText(instruction);
    }
    
/***************************************************************
* 
* ***************************************************************/    
    Boolean northFirst = true;
    Boolean northSecond = true;
    Boolean northThird = true;
    
    public void addCarToNorthQueue(Queue<CarList> northQueue) throws InterruptedException{  
        //make visible
        switch(northQueue.size()){
            case 3: 
                northCar3.setVisible(true);
            case 2: 
                northCar2.setVisible(true);
            case 1: 
                northCar1.setVisible(true);
        }
        
        //make invisible
        switch(northQueue.size()){
            case 0:
                northCar1.setVisible(false);
            case 1: 
                northCar2.setVisible(false);
            case 2: 
                northCar3.setVisible(false);
        }
    }
    
    public void addCarToSouthQueue(Queue<CarList> southQueue) throws InterruptedException{  
        //make visible
        switch(southQueue.size()){
            case 2: 
                southCar2.setVisible(true);
            case 1: 
                southCar1.setVisible(true);
        }
        
        //make invisible
        switch(southQueue.size()){
            case 0:
                southCar1.setVisible(false);
            case 1: 
                southCar2.setVisible(false);
        }
    }
    
    public void addCarToEastQueue(Queue<CarList> eastQueue){
        //make visible
        switch(eastQueue.size()){
            case 3: 
                eastCar3.setVisible(true);
            case 2: 
                eastCar2.setVisible(true);
            case 1: 
                eastCar1.setVisible(true);
        }
        
        //make invisible
        switch(eastQueue.size()){
            case 0:
                eastCar1.setVisible(false);
            case 1: 
                eastCar2.setVisible(false);
            case 2: 
                eastCar3.setVisible(false);
        }
    }
    
    public void addCarToWestQueue(Queue<CarList> westQueue){
        //make visible
        switch(westQueue.size()){
            case 3: 
                westCar3.setVisible(true);
            case 2: 
                westCar2.setVisible(true);
            case 1: 
                westCar1.setVisible(true);
        }
        
        //make invisible
        switch(westQueue.size()){
            case 0:
                westCar1.setVisible(false);
            case 1: 
                westCar2.setVisible(false);
            case 2: 
                westCar3.setVisible(false);
        }
    }
    
    
    
    public void toEast(){
        toEast.setVisible(true);
    }
    public void toEastErase(){
        toEast.setVisible(false);
    }
    public void eastCar4(){
        eastCar4.setVisible(true);
    }
    public void eastCar4Erase(){
        eastCar4.setVisible(false);
    }
    public void eastCar5(){
        eastCar5.setVisible(true);
    }
    public void eastCar5Erase(){
        eastCar5.setVisible(false);
    }
    public void eastCar6(){
        eastCar6.setVisible(true);
    }
    public void eastCar6Erase(){
        eastCar6.setVisible(false);
    }
    
    
    public void toWest(){
        toWest.setVisible(true);
    }
    public void toWestErase(){
        toWest.setVisible(false);
    }
    public void westCar4(){
        westCar4.setVisible(true);
    }
    public void westCar4Erase(){
        westCar4.setVisible(false);
    }
    public void westCar5(){
        westCar5.setVisible(true);
    }
    public void westCar5Erase(){
        westCar5.setVisible(false);
    }
    public void westCar6(){
        westCar6.setVisible(true);
    }
    public void westCar6Erase(){
        westCar6.setVisible(false);
    }
    
    
    public void southCar3(){
        southCar3.setVisible(true);
    }
    public void southCar3Erase(){
        southCar3.setVisible(false);
    }
    public void southCar4(){
        southCar4.setVisible(true);
    }
    public void southCar4Erase(){
        southCar4.setVisible(false);
    }
    
    
    public void northCar4(){
        northCar4.setVisible(true);
    }
    public void northCar4Erase(){
        northCar4.setVisible(false);
    }
    public void northCar5(){
        northCar5.setVisible(true);
    }
    public void northCar5Erase(){
        northCar5.setVisible(false);
    }
    public void northCar6(){
        northCar6.setVisible(true);
    }
    public void northCar6Erase(){
        northCar6.setVisible(false);
    }
    
    
    public void toSouthOrWest(){
        toSouthOrWest.setVisible(true);
    }
    public void toSouthOrWestErase(){
        toSouthOrWest.setVisible(false);
    }
    
    public void toNorthOrEast(){
        toNorthOrEast.setVisible(true);
    }
    public void toNorthOrEastErase(){
        toNorthOrEast.setVisible(false);
    }
    
    /***************************************************************
    *
    * 
    * ***************************************************************/
    public void fromEast(){
        fromEast.setVisible(true);
    }
    public void fromEastErase(){
        fromEast.setVisible(false);
    }
    
    public void fromWest(){
        fromWest.setVisible(true);
    }
    public void fromWestErase(){
        fromWest.setVisible(false);
    }

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrafficModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrafficModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrafficModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrafficModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrafficModel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel east;
    private javax.swing.JLabel eastCar1;
    private javax.swing.JLabel eastCar2;
    private javax.swing.JLabel eastCar3;
    private javax.swing.JLabel eastCar4;
    private javax.swing.JLabel eastCar5;
    private javax.swing.JLabel eastCar6;
    private javax.swing.JLabel fromEast;
    private javax.swing.JLabel fromWest;
    private javax.swing.JLabel greenlight_East;
    private javax.swing.JLabel greenlight_North;
    private javax.swing.JLabel greenlight_Pedestrain;
    private javax.swing.JLabel greenlight_South;
    private javax.swing.JLabel greenlight_West;
    private javax.swing.JLabel instruction;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel north;
    private javax.swing.JLabel northCar1;
    private javax.swing.JLabel northCar2;
    private javax.swing.JLabel northCar3;
    private javax.swing.JLabel northCar4;
    private javax.swing.JLabel northCar5;
    private javax.swing.JLabel northCar6;
    private javax.swing.JLabel pedestrian;
    private javax.swing.JLabel redlight_East;
    private javax.swing.JLabel redlight_North;
    private javax.swing.JLabel redlight_Pedestrain;
    private javax.swing.JLabel redlight_South;
    private javax.swing.JLabel redlight_West;
    private javax.swing.JLabel south;
    private javax.swing.JLabel southCar1;
    private javax.swing.JLabel southCar2;
    private javax.swing.JLabel southCar3;
    private javax.swing.JLabel southCar4;
    private javax.swing.JLabel toEast;
    private javax.swing.JLabel toNorthOrEast;
    private javax.swing.JLabel toSouthOrWest;
    private javax.swing.JLabel toWest;
    private javax.swing.JLabel tovertical1;
    private javax.swing.JPanel trafficLightBackground;
    private javax.swing.JPanel trafficLightBackground1;
    private javax.swing.JPanel trafficLightBackground_North;
    private javax.swing.JPanel trafficLightBackground_North1;
    private javax.swing.JLabel west;
    private javax.swing.JLabel westCar1;
    private javax.swing.JLabel westCar2;
    private javax.swing.JLabel westCar3;
    private javax.swing.JLabel westCar4;
    private javax.swing.JLabel westCar5;
    private javax.swing.JLabel westCar6;
    private javax.swing.JLabel yellowlight_East;
    private javax.swing.JLabel yellowlight_North;
    private javax.swing.JLabel yellowlight_Pedestrain;
    private javax.swing.JLabel yellowlight_South;
    private javax.swing.JLabel yellowlight_West;
    // End of variables declaration//GEN-END:variables

}
